sys_includes = ["stddef.h", "alloca.h", "wchar.h", "features.h", "bits/locale-t.h"]
include_guard = "_RELIBC_STDLIB_H"
trailer = """
long double strtold(const char *nptr, char **endptr);
long double strtold_l(const char *nptr, char **endptr, locale_t _loc);
"""
language = "C"
style = "Type"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true

[export]
exclude = ["relibc_dtold"]
