sys_includes = ["stdint.h", "features.h"]
include_guard = "__LINUX_KEYBOARD_H"
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true
trailer = """
#define KG_SHIFT 0
#define KG_CTRL 2
#define KG_ALT 3
#define KG_ALTGR 1
#define KG_SHIFTL 4
#define KG_SHIFTR 5
#define KG_CTRLL 6
#define KG_CTRLR 7
#define KG_CAPSSHIFT 8

#define NR_SHIFT 9
#define NR_KEYS 256
#define MAX_NR_KEYMAPS 256

#define KT_LATIN 0
#define KT_FN 1
#define KT_SPEC 2
#define KT_PAD 3
#define KT_DEAD 4
#define KT_CONS 5
#define KT_CUR 6
#define KT_SHIFT 7
#define KT_META 8
#define KT_ASCII 9
#define KT_LOCK 10
#define KT_LETTER 11

#define K(t,v) (((t) << 8) | (v))
#define KTYP(x) ((x) >> 8)
#define KVAL(x) ((x) & 0xff)

#define K_F1 K(KT_FN, 0)
#define K_F2 K(KT_FN, 1)
#define K_F3 K(KT_FN, 2)
#define K_F4 K(KT_FN, 3)
#define K_F5 K(KT_FN, 4)
#define K_F6 K(KT_FN, 5)
#define K_F7 K(KT_FN, 6)
#define K_F8 K(KT_FN, 7)
#define K_F9 K(KT_FN, 8)
#define K_F10 K(KT_FN, 9)
#define K_F11 K(KT_FN, 10)
#define K_F12 K(KT_FN, 11)
#define K_FIND K(KT_FN, 20)
#define K_INSERT K(KT_FN, 21)
#define K_REMOVE K(KT_FN, 22)
#define K_SELECT K(KT_FN, 23)
#define K_PGUP K(KT_FN, 24)
#define K_PGDN K(KT_FN, 25)
#define K_MACRO K(KT_FN, 26)
#define K_HELP K(KT_FN, 27)
#define K_DO K(KT_FN, 28)
#define K_PAUSE K(KT_FN, 29)

#define K_ENTER K(KT_SPEC, 1)
#define K_BREAK K(KT_SPEC, 2)
#define K_CAPS K(KT_SPEC, 8)
#define K_NUM K(KT_SPEC, 9)
#define K_HOLD K(KT_SPEC, 10)
#define K_ALT K(KT_SPEC, 12)
#define K_ALTGR K(KT_SPEC, 13)
#define K_CTRL K(KT_SPEC, 14)
#define K_CTRLL K(KT_SPEC, 15)
#define K_CTRLR K(KT_SPEC, 16)
#define K_SHIFT K(KT_SPEC, 17)
#define K_SHIFTL K(KT_SPEC, 18)
#define K_SHIFTR K(KT_SPEC, 19)
#define K_COMPOSE K(KT_SPEC, 127)

#define K_PPLUS K(KT_PAD, 0)
#define K_PMINUS K(KT_PAD, 1)
#define K_PSTAR K(KT_PAD, 2)
#define K_PSLASH K(KT_PAD, 3)
#define K_PENTER K(KT_PAD, 4)
#define K_PCOMMA K(KT_PAD, 5)
#define K_PDOT K(KT_PAD, 6)
#define K_PPLUSMINUS K(KT_PAD, 7)

#define K_DOWN K(KT_CUR, 0)
#define K_LEFT K(KT_CUR, 1)
#define K_RIGHT K(KT_CUR, 2)
#define K_UP K(KT_CUR, 3)

#define K_DGRAVE K(KT_DEAD, 0)
#define K_DACUTE K(KT_DEAD, 1)
#define K_DCIRCM K(KT_DEAD, 2)
#define K_DTILDE K(KT_DEAD, 3)
#define K_DDIERE K(KT_DEAD, 4)

#define K_SHIFTLOCK K(KT_LOCK, 0)
#define K_CONS K(KT_CONS, 0)
"""

[enum]
prefix_with_name = true
